//! AI Director: shot planning, beat analysis, and render sequencing.
//!
//! Ported from S3 Studio's `ai_director/`. Key migration changes:
//!   - No Tauri commands; all invocation is via IPC or internal function calls
//!   - Tier gate uses AppState.tier (HMAC-verified) instead of require_creator_studio()
//!   - Added InitSource enum for keyframe provenance tracking
//!   - Added render_sequence: groups shots by engine for efficient batch execution
//!     (all 1magen keyframes first, then all 3nvizen video segments)
//!
//! Wire types match `vidDirectorApi.ts` for frontend compatibility.

pub mod shot_planner;
pub mod sapi_planner;

use serde::{Deserialize, Serialize};

use crate::LicenceTier;

// ---------------------------------------------------------------------------
// Wire types (match vidDirectorApi.ts)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BeatEntry {
    pub time_ms: u64,
    pub beat_type: String,
    pub energy: f32,
    pub section_label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Section {
    pub start_ms: u64,
    pub end_ms: u64,
    pub label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BeatMap {
    pub bpm: f32,
    pub duration_ms: u64,
    pub beats: Vec<BeatEntry>,
    pub sections: Vec<Section>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Shot {
    pub shot_id: String,
    pub start_ms: u64,
    pub end_ms: u64,
    pub visual_prompt: String,
    pub shot_type: String,
    pub reference_tags: Vec<String>,
    /// How the initial frame for this shot is sourced.
    pub init_source: InitSource,
}

/// How the initial frame for a video shot is sourced. This controls the
/// render pipeline: keyframe-generated shots need an image engine pass
/// before the video engine can extend them; user-provided shots skip the
/// keyframe step entirely.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum InitSource {
    /// Keyframe will be generated by an image engine (e.g. 1magen).
    /// The render_sequence places these in the image batch first.
    KeyframeGenerated {
        /// Prompt for keyframe generation (may differ from shot visual_prompt).
        keyframe_prompt: String,
    },
    /// Initial frame is the last frame of the previous shot.
    /// No keyframe generation needed; video engine continues from prior output.
    PreviousShotEndFrame {
        /// shot_id of the preceding shot.
        previous_shot_id: String,
    },
    /// User has provided the initial frame directly (uploaded image).
    /// No keyframe generation needed.
    UserProvided {
        /// Path or FileRef to the user-supplied image.
        image_path: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShotPlan {
    pub shots: Vec<Shot>,
    pub style_preset: String,
    pub brief: String,
    pub total_duration_ms: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanShotsParams {
    pub audio_path: String,
    pub beat_map: BeatMap,
    pub brief: String,
    pub style_preset: String,
    #[serde(default)]
    pub target_duration_ms: Option<u64>,
    #[serde(default)]
    pub model: Option<String>,
}

// ---------------------------------------------------------------------------
// Render sequence
// ---------------------------------------------------------------------------

/// A single step in the render sequence. Either generate a keyframe image
/// or extend a shot into video.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "engine", rename_all = "snake_case")]
pub enum RenderStep {
    /// Generate a keyframe image via an image engine (e.g. 1magen).
    ImageKeyframe {
        shot_id: String,
        prompt: String,
        /// Index of this keyframe in the overall sequence (for ordering).
        sequence_index: usize,
    },
    /// Generate a video segment from an initial frame via a video engine (e.g. 3nvizen).
    VideoSegment {
        shot_id: String,
        start_ms: u64,
        end_ms: u64,
        visual_prompt: String,
        /// Reference to the initial frame (output of a prior ImageKeyframe step,
        /// or a user-provided image, or the end frame of a previous VideoSegment).
        init_frame_ref: String,
        sequence_index: usize,
    },
}

/// Build a render sequence from a ShotPlan. Groups all keyframe generation
/// steps first (for the image engine), then all video extension steps
/// (for the video engine). This minimizes VRAM swaps between engines.
///
/// Invariant: within each group, steps are ordered by shot sequence
/// (first shot first). Cross-engine dependencies are resolved by the
/// shell router's job graph; we just need the grouping here.
pub fn render_sequence(plan: &ShotPlan) -> Vec<RenderStep> {
    let mut image_steps: Vec<RenderStep> = Vec::new();
    let mut video_steps: Vec<RenderStep> = Vec::new();
    let mut global_idx: usize = 0;

    for shot in &plan.shots {
        // Phase 1: keyframe generation (if needed)
        match &shot.init_source {
            InitSource::KeyframeGenerated { keyframe_prompt } => {
                image_steps.push(RenderStep::ImageKeyframe {
                    shot_id: shot.shot_id.clone(),
                    prompt: keyframe_prompt.clone(),
                    sequence_index: global_idx,
                });
                global_idx += 1;
            }
            InitSource::UserProvided { .. } | InitSource::PreviousShotEndFrame { .. } => {
                // No keyframe generation needed
            }
        }

        // Phase 2: video extension
        let init_frame_ref = match &shot.init_source {
            InitSource::KeyframeGenerated { .. } => {
                // Will be resolved to the output of the ImageKeyframe step
                format!("keyframe:{}", shot.shot_id)
            }
            InitSource::PreviousShotEndFrame { previous_shot_id } => {
                format!("endframe:{}", previous_shot_id)
            }
            InitSource::UserProvided { image_path } => {
                format!("user:{}", image_path)
            }
        };

        video_steps.push(RenderStep::VideoSegment {
            shot_id: shot.shot_id.clone(),
            start_ms: shot.start_ms,
            end_ms: shot.end_ms,
            visual_prompt: shot.visual_prompt.clone(),
            init_frame_ref,
            sequence_index: global_idx,
        });
        global_idx += 1;
    }

    // All image keyframes first (batched for 1magen), then all video segments
    // (batched for 3nvizen). Shell router handles VRAM swap between phases.
    let mut sequence = Vec::with_capacity(image_steps.len() + video_steps.len());
    sequence.extend(image_steps);
    sequence.extend(video_steps);
    sequence
}

// ---------------------------------------------------------------------------
// Tier gate
// ---------------------------------------------------------------------------

/// Check that the current tier allows Creator Studio features.
pub fn require_creator_studio(tier: LicenceTier) -> Result<(), String> {
    match tier {
        LicenceTier::CreatorStudio => Ok(()),
        _ => Err(format!(
            "Creator Studio required (current tier: {})",
            tier.as_str()
        )),
    }
}

// ---------------------------------------------------------------------------
// Public API (called from IPC handler or shim)
// ---------------------------------------------------------------------------

/// Analyse audio file -> structured BeatMap with energy + sections.
pub async fn analyze_audio(
    beats_cache: &crate::beats::BeatsCache,
    audio_path: &str,
    tier: LicenceTier,
) -> Result<BeatMap, String> {
    require_creator_studio(tier)?;

    let path = audio_path.to_string();
    let raw_beat_map = tokio::task::spawn_blocking(move || {
        crate::beats::engine::analyse(std::path::Path::new(&path), None)
    })
    .await
    .map_err(|e| format!("Beat analysis task panicked: {e}"))?
    .map_err(|e| format!("Beat analysis failed: {e}"))?;

    // Convert flat beat timestamps to structured Director BeatMap
    Ok(flat_to_director_beat_map(&raw_beat_map))
}

/// Convert a raw beats engine output to a structured Director BeatMap.
/// Simple heuristic: assign energy based on beat interval variance,
/// assign section labels based on energy contour.
fn flat_to_director_beat_map(raw: &crate::beats::engine::BeatMap) -> BeatMap {
    let beats: Vec<BeatEntry> = raw
        .beats
        .iter()
        .enumerate()
        .map(|(i, &time_ms)| {
            let beat_type = if i % 4 == 0 { "downbeat" } else { "beat" }.to_string();

            // Energy heuristic: beats near section boundaries get higher energy
            let energy = if i % 16 == 0 {
                0.9
            } else {
                0.5 + (i % 4) as f32 * 0.1
            };

            // Section label based on position
            let section_label = match (i * 100) / raw.beats.len().max(1) {
                0..=10 => "intro",
                11..=25 => "verse",
                26..=40 => "pre_chorus",
                41..=55 => "chorus",
                56..=70 => "verse",
                71..=85 => "chorus",
                _ => "outro",
            }
            .to_string();

            BeatEntry {
                time_ms,
                beat_type,
                energy,
                section_label,
            }
        })
        .collect();

    // Build sections from beat labels
    let mut sections: Vec<Section> = Vec::new();
    let mut current_label = String::new();
    let mut section_start = 0u64;

    for beat in &beats {
        if beat.section_label != current_label {
            if !current_label.is_empty() {
                sections.push(Section {
                    start_ms: section_start,
                    end_ms: beat.time_ms,
                    label: current_label.clone(),
                });
            }
            current_label = beat.section_label.clone();
            section_start = beat.time_ms;
        }
    }
    // Close final section
    if !current_label.is_empty() {
        sections.push(Section {
            start_ms: section_start,
            end_ms: raw.duration_ms,
            label: current_label,
        });
    }

    BeatMap {
        bpm: raw.bpm,
        duration_ms: raw.duration_ms,
        beats,
        sections,
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn make_test_plan() -> ShotPlan {
        ShotPlan {
            shots: vec![
                Shot {
                    shot_id: "shot-1".into(),
                    start_ms: 0,
                    end_ms: 5000,
                    visual_prompt: "cityscape at night".into(),
                    shot_type: "wide".into(),
                    reference_tags: vec![],
                    init_source: InitSource::KeyframeGenerated {
                        keyframe_prompt: "neon cityscape, wide angle".into(),
                    },
                },
                Shot {
                    shot_id: "shot-2".into(),
                    start_ms: 5000,
                    end_ms: 10000,
                    visual_prompt: "zoom into neon signs".into(),
                    shot_type: "close".into(),
                    reference_tags: vec![],
                    init_source: InitSource::PreviousShotEndFrame {
                        previous_shot_id: "shot-1".into(),
                    },
                },
                Shot {
                    shot_id: "shot-3".into(),
                    start_ms: 10000,
                    end_ms: 15000,
                    visual_prompt: "crowd dancing".into(),
                    shot_type: "medium".into(),
                    reference_tags: vec![],
                    init_source: InitSource::KeyframeGenerated {
                        keyframe_prompt: "crowd at music festival".into(),
                    },
                },
            ],
            style_preset: "cyberpunk".into(),
            brief: "Music video for electronic track".into(),
            total_duration_ms: 15000,
        }
    }

    #[test]
    fn render_sequence_groups_by_engine() {
        let plan = make_test_plan();
        let seq = render_sequence(&plan);

        // Should have 2 image keyframes first, then 3 video segments
        assert_eq!(seq.len(), 5);

        // First two should be ImageKeyframe
        assert!(
            matches!(&seq[0], RenderStep::ImageKeyframe { shot_id, .. } if shot_id == "shot-1")
        );
        assert!(
            matches!(&seq[1], RenderStep::ImageKeyframe { shot_id, .. } if shot_id == "shot-3")
        );

        // Last three should be VideoSegment
        assert!(matches!(&seq[2], RenderStep::VideoSegment { shot_id, .. } if shot_id == "shot-1"));
        assert!(matches!(&seq[3], RenderStep::VideoSegment { shot_id, .. } if shot_id == "shot-2"));
        assert!(matches!(&seq[4], RenderStep::VideoSegment { shot_id, .. } if shot_id == "shot-3"));
    }

    #[test]
    fn shot2_references_shot1_endframe() {
        let plan = make_test_plan();
        let seq = render_sequence(&plan);

        // shot-2's video segment should reference shot-1's end frame
        if let RenderStep::VideoSegment { init_frame_ref, .. } = &seq[3] {
            assert_eq!(init_frame_ref, "endframe:shot-1");
        } else {
            panic!("Expected VideoSegment at index 3");
        }
    }
}
